### ISSUE TITLE
No dattodb-utils in ubuntu repository(?)

### ISSUE THREAD

**Issue by danielepercivaldi** [datto/dattobd#123]
My environment:
linux ubuntu 14.04 server LTS
kernel 4.4.0-101-generic

I followed the instructions here https://github.com/datto/dattobd/blob/maste/INSTALL.md#debianubuntu-lts and dattodb-utils package is not found. Why?

**Comment by crawfxrd** [comment]
Are you on a 32-bit system?

**Comment by danielepercivaldi** [comment]
Oops. Yes. Any suggestion?

**Comment by crawfxrd** [comment]
The easiest right now would be to [install from source](../blob/master/INSTALL.md#from-source). I've created #124 to simplify this case.

**Comment by Conan-Kudo** [comment]
So this is not really an issue, as Datto only officially supports x86_64 / amd64.

**Comment by tcaputi** [comment]
I would actually advocate for supporting 32 bit. dattobd will work on both, even if most of the programs built on top of it only support x86_64.

**Comment by nixomose** [comment]
Nay brother. I got it working on a raspberry pi. I had to remove the x86 instructions but that's it.

**Comment by danielepercivaldi** [comment]
Hi @nixomose .
What do you mean with "I had to remove the x86 instructions but that's it."?

**Comment by nixomose** [comment]
there's a few lines of code that have to do with erk I forget already, but atomically doing something to the processor. they're inline assembly instructions if I remember correctly, and they're x86 specific.
They'll be obvious because you get syntax errors on the build. just remove those functions and references to them and then it builds clean.
