### ISSUE TITLE
Regarding dirty file handling

### ISSUE THREAD

**Issue by c3mb0** [datto/dattobd#134]
How does `dattobd` handle large amounts of `mmap`'ed files during transitions? Are they properly reflected to the updated image?

**Comment by nixomose** [comment]
Tom can confirm, but dattobd freezes the filesystem and that should call sync first, so whatever is in any page buffers, should get synced before the snapshot is taken.
I'm not an expert on how lazily or not mmap flushes writes, but if they make it to the page cache, it should be in the snapshot.

**Comment by tcaputi** [comment]
Changes made to mmap'ed files are not flushed to disk until a call to `msync()`. Therefore, mmaped changes are not guaranteed to be reflected in the dattobd snapshot until that happens. There isn't a great way around this since dattobd operates at the block device layer. However, many applications such as MySQL have functions that allow you to "quiesce" the state of your data on disk until a snapshot is taken. In MySQL, this is done with `FLUSH TABLES WITH READ LOCK;` and `UNLOCK TABLES;` to continue normal operation
