### ISSUE TITLE
Unable to install via DKMS on CloudLinux (CentOS 6)

### ISSUE THREAD

**Issue by cseufert** [datto/dattobd#136]
Hi,

I used the RHEL/CentOS pacakges install the dattbd driver and utils, however I cant load the kernel module.

```
# modprobe -v dattobd
insmod /lib/modules/2.6.32-531.17.1.lve1.2.57.el6.x86_64/kernel/drivers/block/dattobd.ko
FATAL: Error inserting dattobd (/lib/modules/2.6.32-531.17.1.lve1.2.57.el6.x86_64/kernel/drivers/block/dattobd.ko): Unknown symbol in module, or unknown parameter (see dmesg)

# dmesg | tail
...
[44213954.644909] dattobd: Unknown symbol part_nr_sects_read
```

I am unsure how to proceed from here.

**Comment by crawfxrd** [comment]
This is a bug with the OpenVZ kernel backport patches.

They backported `part_nr_sects_read` as a function, but never exported it. So we detect the function, but as an external module we can't use it.

**Comment by cseufert** [comment]
Thanks, 

So to use dattobd I would have to recompile the kernel with a patch for the part_nr_sects_read code?

**Comment by tcaputi** [comment]
You could do that but it would probably be easier to just change the kernel module instead. You should be able to make it work by literally copying and pasting that function into dattobd.c. Just change the name of the function and call that instead here: https://github.com/datto/dattobd/blob/master/src/dattobd.c#L495

**Comment by crawfxrd** [comment]
I don't understand their workflow, but I made an upstream ticket for this: https://bugs.openvz.org/browse/OVZ-7071

**Comment by crawfxrd** [comment]
openVZ will not fix this.

So two things off the top of my head we could do:
- Not give special attention to openVZ 6 based distros
- Delete `configure-tests/feature-tests/part_nr_sects_read.c` for CentOS 6 packages

Option 1 means users _will_ have to remove this file (or the `HAVE_PART_NR_SECTS_READ` define in `kernel-config.h`) and rebuild/install every time they update dattobd.

Option 2 means RHEL/CentOS 6 _could_ have unsafe behavior if they backport the function in the future (but should otherwise still work).

**Comment by crawfxrd** [comment]
Option 2 will not work if they are using another kernel, such as ELRepo.

The workaround for this on CloudLinux is:
```
dkms uninstall dattobd/<version>
rm /usr/src/dattobd-<version>/configure-tests/feature-tests/part_nr_sects_read.c
dkms build dattobd/<version>
dkms install dattobd/<version>
modprobe dattobd
```

**Comment by crawfxrd** [comment]
This upstream fix has been released in [042stab136.1](https://wiki.openvz.org/Download/kernel/rhel6/042stab136.1).
