### ISSUE TITLE
Cant compile on Rock64

### ISSUE THREAD

**Issue by bphermansson** [datto/dattobd#138]
I try to compile dattobd on a Rock64 but get errors:

```
make[2]: Entering directory '/usr/src/linux-headers-4.4.77-rockchip-ayufan-136'
  CC [M]  /home/rock64/Downloads/dattobd/src/dattobd.o
/home/rock64/Downloads/dattobd/src/dattobd.c: In function ‘disable_page_protection’:
/home/rock64/Downloads/dattobd/src/dattobd.c:4745:9: error: implicit declaration of function ‘read_cr0’ [-Werror=implicit-function-declaration]
  *cr0 = read_cr0();
         ^
/home/rock64/Downloads/dattobd/src/dattobd.c:4746:2: error: implicit declaration of function ‘write_cr0’ [-Werror=implicit-function-declaration]
  write_cr0(*cr0 & ~CR0_WP);
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:264: recipe for target '/home/rock64/Downloads/dattobd/src/dattobd.o' failed
```

```
uname -a
Linux rock64 4.4.77-rockchip-ayufan-136 #1 SMP Thu Oct 12 09:14:48 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by crawfxrd** [comment]
dattobd will only work on x86 due to how it hooks into the syscall table for maintaining consistency between mounts.

You could try removing [the relevant code](https://github.com/datto/dattobd/blob/6a658cb217c528aaa50f1bf729a7940b54e141c4/src/dattobd.c#L4321-L4820), but I would expect there to be other issues that prevent it from running on ARM.

@nixomose do you remember if you had to do anything else when you tried running dattobd on ARM?

**Comment by nixomose** [comment]
actually if I remember right, that's all I did. I removed the mount hook x86 specific stuff, set the flag to not try the mount hook and voila it all worked.
I don't remember how extensive the testing was but I know it with through the process of taking a snapshot when I tried.

**Comment by bphermansson** [comment]
I commented out the code and managed to build the module. But modprobe wont find it and insmod crashes with a seg fault.

**Comment by nixomose** [comment]
you ran depmod -a after you installed it?

**Comment by bphermansson** [comment]
No :) Then I did, and it worked. Thanks!
