### ISSUE TITLE
debian package outdated and repository for buster doesn't exist

### ISSUE THREAD

**Issue by yennor** [datto/dattobd#204]
On the debian repository https://cpkg.datto.com/datto-deb/public/stretch  the newest release is 0.10.9-23.3debian9 which seems to be two releases in behind.
Also, debian buster was officially released a while ago, so it would be nice, if there would also be a buster repository.

**Comment by Conan-Kudo** [comment]
There's been some complications that have delayed some work that I need to do to publish updated packages to `cpkg.datto.com`. Similarly, there's some work I need to do first to get Debian 10 builds enabled to publish, so that's going to take some time.

No promises, but I'm working as quickly as I can to get it out the door.

**Comment by Conan-Kudo** [comment]
This is now fixed. The latest release has been published and Debian 10 support has been added.
