### ISSUE TITLE
Kernel version 

### ISSUE THREAD

**Issue by pskaurav** [datto/dattobd#238]
Hi,

Driver loading is failing with ïnvalid module format on centos 7. After debugging, i have found that build machine kernel(3.10.0-1160.2.2.el7.x86_64) and client machine kernel(3.10.0-123.el7.x86_64) is different. I have read that build machine kernel and client machine must be exactly match to load driver.

Is there any way to load driver on client where kernel is different than build machine?

**Comment by nixomose** [comment]
nope.

But I suppose it depends what you mean by different.
when you build a kernel module, it saves a magic number generated by the kernel, which I forget what it's based on (if it's kernel configuration settings or version number, etc) but basically the kernel has to make sure that it only loads kernel modules that were built for it.

if it doesn't, there's no guarantee that the interface that the kernel module was built against matches the interface on the running kernel. 
the linux kernel is notorious for a) keeping the interface to userspace perfectly stable, and b) keeping the interface within the kernel wildly in flux and unmaintainable, big things break from minor release to minor release all the time

So if you're going to load something into the kernel, you better be real sure, it was built against the running kernel, because you can be pretty confidence it has a good chance of failing if you try to load it into a different ont.

**Comment by pskaurav** [comment]
Thanks a lot.
We can close this issue.
