### ISSUE TITLE
How to 'revert to snapshot'?

### ISSUE THREAD

**Issue by JKozarac22** [datto/dattobd#247]
I don't know am I missing something but I don't understand how to 'revert to snapshot'?

I have three VGs > vg1 is system partition, vg2 is /Live and vg3 is /Backup. I followed all the commands for creating the snapshot of the /Live, dd that snapshot to /Backup, putting a snapshot into incremental mode, ...

Then, I deleted some data from the /Live folder. **Can you tell me, please, how can I 'revert to snapshot' from /Backup? What command can I use?** 

Additional question > /Live is 70 GBs and /Backup is 25 GBs. I put some 800 MBs data in /Live and when I created the first snapshot, datto file was 7 GBs. After that, I did dd if=/Live/datto0 of=/Backup/live-bckp bs=1M, and all the space of /Backup (25 GBs) was consumed. Is it OK?

**Comment by nixomose** [comment]
it doesn't work like that.
dattobd isn't a complete backup solution, it is a piece of the puzzle.
when you make a snapshot, you are then supposed to back up the data in the snapshot to some other external storage. the purpose of dattobd is to provide a point in time consistent image of the source volume so you can safely back it up while the live volume it is snapshotting is still in use.

**Comment by nixomose** [comment]
I'm not sure I understand your second question. actually let me assure you I don't understand your second question.
 you tried to dd the datto0 block device which is a snapshot of a 70 gig volume into a file on a volume with 25 gig of space.
so, yeah it filled up the 25 gig, and then it failed because it ran out of space.
not sure what you're trying to do.
if you want to back up a 70 gig image, you need 70 gig to put it on.

**Comment by JKozarac22** [comment]
> 
> 
> it doesn't work like that.
> dattobd isn't a complete backup solution, it is a piece of the puzzle.
> when you make a snapshot, you are then supposed to back up the data in the snapshot to some other external storage. the purpose of dattobd is to provide a point in time consistent image of the source volume so you can safely back it up while the live volume it is snapshotting is still in use.

HDD2 is vg2 and it is point to /Live
HDD3 is vg3 and it is point to /Backup

I thought that my HDD3 is my some kind of _external_ storage. That's why I made dd from /Live/datto0 to them. Or am I not right? I thought that I can do 'revert to snapshot' because /Live and /Backup are different VGs and HDDs.



> 
> 
> I'm not sure I understand your second question. actually let me assure you I don't understand your second question.
> you tried to dd the datto0 block device which is a snapshot of a 70 gig volume into a file on a volume with 25 gig of space.
> so, yeah it filled up the 25 gig, and then it failed because it ran out of space.
> not sure what you're trying to do.
> if you want to back up a 70 gig image, you need 70 gig to put it on.

:)
Sorry. I thought that I don't need as much space in /Backup as much space in /Live isn't consumed. datto0 file is about 7 GBs and my /Backup is 25 GBs.
I hope you understand me, I don't know English well :(
And I'm not Linux expert but I'm trying to learn it.

**Comment by nixomose** [comment]
okay so I guess the missing piece here is dd.
dd stands for data duplicator (if I remember right) and it is a really simple tool.
it copies data from if to of verbatim, as is.
so when you did this:

` dd that snapshot to /Backup`

what you did was take the point in time image of /Live that dattobd provides and copied it byte for byte to a file /Backup. Unless you copied over the device itself.
either way, it would have failed because you need just as much space in the destination as the source if you're going to dd data anywhere.
don't worry about dattobd's internal files it has nothing to do with the amount of data you're backing up or anything.

I think the problem is this setup is a bit simpler than you're thinking it is. Nothing magical is going on here (Except inside dattobd) but from a user's point of view, the datto0 device is a volume of data, you can copy it somewhere, you might even be able to mount it readonly (if it's not xfs, long story) and copy files off it.

if you want to make a copy of the changed data only, then you'd need to use a utility that does that. I think that tool is provided in the dattobd repo as a sample. I haven't used it in a long time so I forget the details
but even that, what it does it just copy the few blocks that changed since the last backup to another destination, and if that destination didn't already have a copy of the rest of the data that was on the volume you're backing up, then just the delta data is useless.

What I'm getting at is that dattobd is a tool for performing one step of the backup process, you need to think about what you're trying to do and how to piece to the tools together to get what you want.

I'm pretty sure there are existing backup tools some of which are based on dattobd as well that do more of the big picture process of maintaining backups

**Comment by JKozarac22** [comment]
**nixomose**, thank you for your time and patience :)

I think this is too much for me in the moment :(
But, I will put here my lab conf so we can go through it if you want >

**df -h** >
/dev/mapper/vg2-Live   xfs        70G  280M   70G   1% /Live
/dev/mapper/vg3-Backup xfs        25G   33M   25G   1% /Backup

**vgs** >
vg2   2   1   0 wz--n-  99.99g 29.99g
vg3   1   1   0 wz--n- <25.00g     0

**lvs** >
Live   vg2 -wi-ao----  70.00g
Backup vg3 -wi-ao---- <25.00g

If I understand you, the first problem is that I have too small vg3 because I want to backup data from vg2 to vg3 or 70 GBs to 25 GBs. I put it like this on purpose because I thought that the LVM snapshot do not need to be the same size as the source. I know, it depends on the amount of change on disks but, like I said, I thought that I'll be OK with 30 % of the size of the source. Let's move on.

I did the next commands >
**dbdctl setup-snapshot /dev/mapper/vg2-Live /Live/datto 0**

**df -h** >
/dev/mapper/vg2-Live   xfs        70G  7.3G   63G  11% /Live
/dev/mapper/vg3-Backup xfs        25G   33M   25G   1% /Backup

**blkid** >
/dev/mapper/vg2-Live: UUID="e3bcff83-d191-466c-bc02-c45d9ba13e5c" TYPE="xfs"
/dev/mapper/vg3-Backup: UUID="dca0c13a-d30d-47af-a21e-aa5816ae1dda" TYPE="xfs"
/dev/datto0: UUID="e3bcff83-d191-466c-bc02-c45d9ba13e5c" TYPE="xfs"

**dd if=/dev/datto0 of=/Backup/Live-bckp bs=1M** >
dd: error writing ‘/Backup/Live-bckp’: No space left on device
25554+0 records in
25553+0 records out
26794328064 bytes (27 GB) copied, 481.673 s, 55.6 MB/s

**df -h** >
/dev/mapper/vg2-Live   xfs        70G  7.3G   63G  11% /Live
/dev/mapper/vg3-Backup xfs        25G   25G  460K 100% /Backup

So, this is the first problem, isn't it?
------------------------------------------------------------------------------------
Let's reverse situation with disks sizes. I 'revert to snapshot' of my VM before previously commands. I know how to do it in VMware vCenter :D

**df -h** >
/dev/mapper/vg2-Backup xfs        70G   33M   70G   1% /Backup
/dev/mapper/vg3-Live   xfs        25G  1.6G   24G   7% /Live

**vgs** >
vg2   2   1   0 wz--n-  99.99g 29.99g
vg3   1   1   0 wz--n- <25.00g     0

**lvs** >
Backup vg2 -wi-ao----  70.00g
Live   vg3 -wi-ao---- <25.00g

I did the next commands >
**dbdctl setup-snapshot /dev/mapper/vg3-Live /Live/datto 0**

**df -h** >
/dev/mapper/vg2-Backup xfs        70G   33M   70G   1% /Backup
/dev/mapper/vg3-Live   xfs        25G  4.1G   21G  17% /Live

**blkid** >
/dev/mapper/vg3-Live: UUID="dca0c13a-d30d-47af-a21e-aa5816ae1dda" TYPE="xfs"
/dev/mapper/vg2-Backup: UUID="e3bcff83-d191-466c-bc02-c45d9ba13e5c" TYPE="xfs"
/dev/datto0: UUID="dca0c13a-d30d-47af-a21e-aa5816ae1dda" TYPE="xfs"

**dd if=/dev/datto0 of=/Backup/Live-bckp bs=1M** >
25596+0 records in
25596+0 records out
26839351296 bytes (27 GB) copied, 479.883 s, 55.9 MB/

**df -h** >
/dev/mapper/vg2-Backup xfs        70G   26G   45G  36% /Backup
/dev/mapper/vg3-Live   xfs        25G  4.1G   21G   17% /Live

**dbdctl transition-to-incremental 0**

**df -h** >
/dev/mapper/vg2-Backup xfs        70G   26G   45G  36% /Backup
/dev/mapper/vg3-Live   xfs        25G  1.8G   24G   8% /Live

I know, I can do my work now and, in some point, I can move back incremental to snapshote mode and then update the Live-bckp file with changes. And I know, it will work like a charm.
But, I don't want to do that in this point. I want to do something else. I made some changes in /Live folder > I deleted some previously data and I copy some new data into the folder. And now, I want to 'revert to snapshot' I made it with my first command dbdctl setup-snapshot /dev/mapper/vg3-Live /Live/datto 0. That snapshot was dd, wasn't it > dd if=/dev/datto0 of=/Backup/Live-bckp bs=1M.

**So, how to 'revert to snapshot' after the last command dbdctl transition-to-incremental 0** :)

**Comment by nixomose** [comment]
okay. all good questions. I see what you're trying to do and you're mostly there.

```
dd: error writing ‘/Backup/Live-bckp’: No space left on device
So, this is the first problem, isn't it?
```

Yes, as you show, you can't copy 75 gigs of data into a 25 gig volume.

` I put it like this on purpose because I thought that the LVM snapshot do not need to be the same size as the source.`

At no point was I considering lvm as being part of the picture and for our purposes, it is not.
lvm snapshots are a completely different and separate ball of magic from dattobd. You might want to look into lvm snapshots because if you're already using lvm, you may get better utility out of that than dattobd, but let's continue.

From dattobd's point of view, it is snapshotting a block device. It does not care if it's a partition on a spinning disk, a loop device or an lvm volume or anything else. It simply sees a block device and makes a another block device that represents the original one at a point in time.

So think about all of this without lvm, because it's only confusing things. Given that, I think you already see, all you're doing is trying to copy 75 gigs of data into 25 gigs and it won't fit, thus the no space left on device error.

As for the second part....

It all makes sense and is correct, what you have basically done is taken the smaller 25 gig volume, and used dattobd to get a point in time view of it, and then you dd'd that point in time image to a file on /Backup called Live-bckp.

If you were so inspired, you could actually attach a loop device to that file and mount it somewhere and see and interact with  that volume. You could copy files off it, or whatever. Keep in mind however, that xfs specifically has trouble when it sees two mounted volumes with the same uuid, so if you're going to do that, make sure you unmount the real one first.
Let's continue...

 `I know, I can do my work now and, in some point, I can move back incremental to snapshote mode and then update the Live-bckp file with changes. And I know, it will work like a charm.`

Yes, because you'd basically be doing the same thing as the first time, take a [newer] snapshot of the /Live volume and copy its entire contents over the file in /Backup/Live-bckp, and yes that would work fine.

```
But, I don't want to do that in this point. I want to do something else. I made some changes in /Live folder > I deleted some previously data and I copy some new data into the folder. And now, I want to 'revert to snapshot' I made it with my first command dbdctl setup-snapshot /dev/mapper/vg3-Live /Live/datto 0. That snapshot was dd it, wasn't it > dd if=/dev/datto0 of=/Backup/Live-bckp bs=1M.

So, how to 'revert to snapshot' after the last command dbdctl transition-to-incremental 0 :)
```

So think about what you've got here. You've got your /Live volume which is now missing data that you deleted, and you want to restore it from the backup.
Basically all you need to do, is dd if=/Backup/Live-bckp of=/Live bs=1M
You just want to take the entire image of what you backed up, and write over the original disk with it.

a few points: you better unmount /Live before you do that, or you're just going to make a giant mess.

you could also optionally, as I mentioned before, make a loop device (losetup -r /dev/loop1 /Backup/Live-bckp) and then mount it (mount /dev/loop1 /mnt) and have access to the backed up filesystem as it existed when you took the snapshot.

again this is just an xfs thing (ext doesn't have this problem) if you do that, make sure you unmount the original /Live first. So in order to restore specific files for example, you'd have to unmount /Live, make the loop device, mount it, copy the files you want to restore somewhere else, unmount the loop device, remove the loop, mount the original /Live, then copy the stuff from the temporary place back into /Live.
Again, this is just a side effect of xfs.

But if you want to just replace the whole thing as is, (or rather as it was) you 1) unmount /Live 2) dd if=/Backup/Live-bckup of=/Live bs=1M  then 3) mount /Live again and you should be right back where you were.

this is a very manual process to get what you want done, but it will work.

Again, this is a very heavy handed way of doing what you want, it will work, but manually copying over whole volumes with dd is a lot of disk copying most of which is probably unnecessary, but you need a real backup application to do it all the 'right' way.

I would also suggest again taking a look at lvm snapshots, they might also do what you want.

**Comment by JKozarac22** [comment]
**nixomose**, thank you one more time for your time.

Unfortunately, I was busy with other stuff at work and I wasn't here but yesterday I took some time and did the homework with LVM snapshots again. I think I got it :)

The next week, I hope, I'll have much time at work so I'll read your answers again and I'll try to solve my _snapshots challenge_. Wish me luck :)

Thank you, thank you!
