### ISSUE TITLE
redundant read problem when reading from snapshot

### ISSUE THREAD

**Issue by lkkey80** [datto/dattobd#27]
when read request comes to  snapshot, dattobd firstly read all Bios from the base device and then it replace the bios in cow. Bios of read request that also in cow are read twice, may it be less efficent?especially for cow data is large.
how about first check whether the read bio is in cow, if it is, read it just from cow. if not, read it from base device?

**Comment by tcaputi** [comment]
I will look into this when I get some time. It was originally done like that because there was a bug in the code responsible for filling in small sections of a large read request that was causing corruption. At the time it was easier to just read from the base device and then overwrite. I will look into this sometime this week.

**Comment by tcaputi** [comment]
I fixed this is c6329. However, we ran some tests and found < 1 MB per second improvement. We will still push the change though, once it has gone through our QA system.

**Comment by lkkey80** [comment]
when a snapshot exsits for a very long time, or more accurately file system's content changes quickly and generates massive cow data, maybe it will show big  improvement both in speed and i/o utils.

**Comment by lkkey80** [comment]
when a snapshot exsits for a very long time, or more accurately file system's content changes quickly and generates massive cow data, maybe it will show big improvement both in speed and i/o utils. @tcaputi

**Comment by lkkey80** [comment]
I checked your commit c6329. refer to "we ran some tests and found < 1 MB per second improvement", I think another reason may be the percent of one bio to be read is completely in base device or cow file is not high. A possible example is, 90% data of the bio  to be read lay in cow file and only 10% data lay in base device, If we can just read 10% data from the base device and 90% data from the cow file, maybe it will show a great improvement in all circumstance. we may need a judgement algorithm to evaluate if we should do the "separate read and combine trick"  to achieve maximum performance. @tcaputi

**Comment by tcaputi** [comment]
Most use cases don't involve very much data in the COW file, since most disks are not under such intense I/O that the entire volume changes. That said our test wrote 1GB of data to a 12G volume on both SSD and spinning disks (if i remember correctly), which is a fairly high percent change.

**Comment by lkkey80** [comment]
To achieve maximum performance, do you have a plan to solve the redundant read issue when ' one bio to be read from snapshot isn't completely in base device or cow file ' . BTW, device mapper's split_io can perfectly solve the issue.

**Comment by tcaputi** [comment]
> BTW, device mapper's split_io can perfectly solve the issue.

I'm not quite sure what you mean by this. I am not familiar with that function and a quick search of the Linux kernel source doesn't show any results. There is the struct member dm_target->split_io, but that refers to a chunk size for raid devices, which doesn't really help us in this case. On most spinning disks, this solution (although it appears less efficient) will actually be faster anyway since it will do 2 sequential reads, as opposed to several random reads.

As a side note, we looked at our test data from yesterday again today since the numbers seemed off. It turns out our tests were only writing 52MB of data onto a 10GB volume, so today we ran the tests again with more COW data. It is not possible to have more than 50% COW data (since at that point half of the disk is COW data and half of the disk is new data). We should have results for a 40% COW data volume tomorrow, but we did get some numbers for 10% COW data (the default maximum amount of COW data allowed in a snapshot):

```
HEAD (commit c6329)
snapshot to /dev/null   134 MB/s
/dev/sda4 to /dev/null  188 MB/s

Release 0.9.3
snapshot to /dev/null   124 MB/s
/dev/sda4 to /dev/null  175 MB/s
```

So we did get a fairly significant bump in performance from this change.

**Comment by lkkey80** [comment]
newer kernel changes the function name, as to device mapper's split_io can perfectly solve the issue, what I mean is, if a bio is larger than the unit size of cow, device mapper clone and split the bio by the unit size of cow. so it can easily make sure that all bios send to snapshot is completely  filled in base device or cow file, read bio send to snapshot device is boundary aligned.
a read bio send to snapshot(dattobd):
bio     |------A-----|------B----|  A, B represents two segments of the bio.
A may be mapped to base device and B may be mapped to cow file, so we have redundant read.  first read A,B segment from base device then read them from cow file to overwrite.

a read bio send to snapshot(device mapper):
since the module clone and split bio according to the chunk size of snapshot(same as Section of dattobd), so redundant read will be eliminated.

**Comment by lkkey80** [comment]
split_io' entry in newer kernel should be in drivers/md/dm.c:
/*
1713  * Entry point to split a bio into clones and submit them to the targets.
1714  */
1715 static void __split_and_process_bio(struct mapped_device *md,
1716                                     struct dm_table *map, struct bio *bio)

**Comment by tcaputi** [comment]
We cannot easily use `__split_and_process_bio()` from device mapper, because this function relies heavily on being backed by the device mapper infrastructure (which we currently do not). This function is also not available to kernel modules (or even outside of dm.c) so we would need to re-implement it from scratch. I can look at this later, but I am currently busy with other work. As always, you are free to submit a pull request and we can review it and QA it with our testing system. If you would like, you can reopen this ticket so it remains visible as an issue or you can open a new ticket.
