### ISSUE TITLE
Request for some kind of status sub-command

### ISSUE THREAD

**Issue by ahmgithubahm** [datto/dattobd#3]
Loving the potential of dattobd now it's open source.  One thing I think would be a great enhancement would be a dbdctl sub-command to output the status (with a choice between nicely formatted, and parseable) to allow both humans and scripts to find out the status of dattobd devices, e.g. their existence, the devices being snapshotted, the paths of COW files, maybe even an idea of the amount of changed data.  Is this something in the pipeline?

**Comment by tcaputi** [comment]
Thanks a lot for the interest. This functionality is actually currently available, although not in dbdctl. To view the status of your snapshots, simply read /proc/datto-info. This is a json encoded file that will tell you the size and current state of your snapshots. We could probably document this file a little better, so I will leave the issue open until I do that. In the meantime, I will tell you what the states mean, since they are represented as integers.

5 = unverified snapshoot
4 = unverified incremental
3 = active snapshot
2 = active incremental
1 = dormant snapshot
0 = dormant incremental

**Comment by ahmgithubahm** [comment]
Thanks, will have a play around.
