### ISSUE TITLE
Driver not loading snapshots/Incrementals after reboot

### ISSUE THREAD

**Issue by snmpbuddy** [datto/dattobd#31]
Built and installed 0.9.6 version of dattobd and have run it in snapshot mode and then rebooted the machine. on reboot  cat /proc/datto-info shows no devices. There is no /dev/datto* devices. Checked that the module was loading in initramfs. Attempting to reload-snapshot also does not work as the device is not created under /dev. Is there any configuration we are missing to make this persist across reboots and have it start tracking changes before the volumes are mounted as read write

Thanks
Shiva

**Comment by tcaputi** [comment]
Take a look at the `reload-snapshot` and `reload-incremental` commands in dbdctl. The driver does not persist state on its own across a reboot. These 2 commands are designed to run early during the reboot process (or at least before the relevant volumes are mounted read/write). These commands effectively inform the driver to be prepared for a volume to be mounted. Later, when the volume is actually mounted, the driver can properly read the cow file and reload its state. Keep in mind the cow file path specified to these commands is RELATIVE to the mountpoint (not `/`).

Unfortunately, getting this to work is different on every distribution. In general terms, what you need to do is:

1.  Add the dbdctl binary and dattobd module to the initramfs.
2.  Write a quick script to the initramfs to call the reload commands you need.
3.  Add the script to the initramfs so that it runs before volumes are mounted RW

Every initramfs will have a different system (for instance, dracut has a local-premount directory IIRC) for getting scripts to run before volumes are mounted.
