### ISSUE TITLE
cowfile size limit

### ISSUE THREAD

**Issue by gopalnaidu** [datto/dattobd#33]
Hi,

I have a query about cowfile max size limit and max free space required to create a snapshot.
I created a snapshot for a 800gb drive which has 150gb free space available. After creating the snapshot a cowfile created with 97gb. I want to decrease cowfile size to as less as possible. What is the calculation i have to follow to get the max cowfile size(fallocate) to create while creating a snapshot.

I tried using a machine with 185gb data and 27 gb free space. After creating snapshot cowfile occupied entire freespace.

What is the free space required in the mountpoint to create a snapshot.

Thanks ..

**Comment by tcaputi** [comment]
I assume you actually want the mimimum cow file size. The way that dattobd works, any time a write is done to the underlying volume, the original data is copied into the cow file. When that file fills up, the driver can no longer maintain a snapshot since it can't copy the original data anywhere.

So to answer your question, the minimum cow file size is equal to the amount of writes you will be doing to the original volume while you need the snapshot active. The default guess that dattobd makes is 10% of the disk, which can be overkill if you don't do that much writing.
